import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { LangProvider, translate } from '../i18n/index.js';
import { CircleSurface } from './screens/CircleSurface.js';
import { ConductFactLines } from './components/ConductFacts.js';
import { AtomicFundingModal } from './panels/AtomicFundingModal.js';
import { CircleArbiter, viewerCircleShare } from './components/CircleArbiter.js';
import { circleFixture, viewer } from '../../tests/first-circle-phones/fixtures.js';
import { Role } from '../escrow-engine/types.js';
import { writeCachedCommunityBonds } from '../arbiters/bonded-pool-cache.js';
import type { VerifiedBond } from '../bond-multisig/bond-announcement.js';
const storage=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v)}});
const {parent,share:base}=circleFixture('held');
const arbiter='b'.repeat(64), other='c'.repeat(64);
const share={...base,participants:{...base.participants,[Role.ARBITER]:arbiter}};
const wrong={...share,id:'other-share',participants:{...share.participants,[Role.BUYER]:other,[Role.ARBITER]:other}};
const names={[arbiter]:'Jet Arbiter',[parent.initiator.pubkey]:'Circle Host',[other]:'Other Arbiter'};
const noop=async()=>{};
const render=(states: typeof share[])=>renderToStaticMarkup(<LangProvider><CircleSurface parent={parent} escrows={new Map([parent,...states].map(s=>[s.id,s]))} viewerPubkey={viewer} childrenLoaded backLabel="Browse" profileNames={names} kind0Enabled onBack={()=>{}} onLock={noop} onClaim={noop} onNextRound={()=>{}} onRefresh={noop}/></LangProvider>);
assert.equal(viewerCircleShare([wrong,share],parent.id,viewer),share);
writeCachedCommunityBonds(share.community!,[{npub:arbiter,community:share.community!,address:'verified-bond',lockUntil:970000,actualSats:100000n,claimedSats:100000n,funded:true,active:true} as VerifiedBond]);
const seated=render([wrong,share]);
assert.match(seated,/Arbiter: Jet Arbiter/);
assert.match(seated,/100,000 sats at stake/);
assert.match(seated,/100,000 sats locked until block 970,000/);
assert.match(seated,/Circle Host/);
assert.match(seated,/Assigned per share/);
assert.doesNotMatch(seated,/Arbiter: Other Arbiter/);
assert.match(seated,/Public record not loaded yet/,'unknown conduct is not reported as zero');
const unresolved=render([wrong]);
assert.match(unresolved,/Assigned when you lock/);
assert.doesNotMatch(unresolved,/Arbiter: Other Arbiter/);
const conduct=renderToStaticMarkup(<LangProvider><ConductFactLines record={{marks:0,complete:true,trades:[],standing:{sellerSpeed:null,arbiterSpeed:{medianSeconds:120,samples:3},settledTrades:4,bonded:null,newHere:false}}}/></LangProvider>);
assert.match(conduct,/Rules within 2 minutes \(median of 3\)/);
assert.match(conduct,/4 trades settled on chain/);
const confirmation=renderToStaticMarkup(<LangProvider><CircleArbiter share={share} profileNames={names} kind0Enabled/></LangProvider>);
assert.match(confirmation,/Arbiter: Jet Arbiter/);
const modal=renderToStaticMarkup(<LangProvider><AtomicFundingModal escrowId={share.id} custodyState={share} profileNames={names} kind0Enabled amountMsats={1000000} ctaLabel="Lock my share" fundAndLock={async()=>({kind:"aborted" as const})} getOnchainInfo={async()=>({} as any)} lockAndPublish={noop} onClose={()=>{}}/></LangProvider>);
assert.match(modal,/Arbiter: Jet Arbiter/);
assert.match(modal,/Held by/);
assert.doesNotMatch(modal,/Notes issued by/);
storage.clear();
assert.match(render([share]),/Bond record not loaded yet/);
assert.doesNotMatch(render([share]),/has no bond/);
for(const lang of ['en','es','fr','sw'] as const) for(const key of ['arbiter','perShare','assignedOnLock','bondTerm','bondUnknown','conductUnknown']) {
 const text=translate(lang,`circle.${key}`,{name:'Jet',amount:'100',block:'970,000'});
 assert(!text.includes('circle.')&&!text.includes('{'),`${lang}/${key} translated`);
}
console.log('PASS circle arbiter: own share, host, verified bond term, unresolved assignment and four languages');
