import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { LangProvider, translate } from "../i18n/index.js";
import { listing } from "../../tests/first-circle-phones/fixtures.js";
import { ecashHoldingPeriod, BitcoinCustody, EcashCustody } from "./components/MoneyCustody.js";
import { LivenessSignal } from "./components/LivenessSignal.js";
import { readLivenessBonds } from "../arbiters/liveness-evidence.js";
import { MAINNET } from "../bond-multisig/multisig.js";
import { buildBondAnnouncementEvent } from "../bond-multisig/bond-announcement.js";
import { finalizeEvent, getPublicKey } from "nostr-tools/pure";
import { computeChamaLiveness } from "../arbiters/live-chama.js";
import { loadCoordinatedLiveness, readCachedLiveness, resetLivenessCoordinator } from "../arbiters/liveness-coordinator.js";
const data = new Map<string, string>();
Object.defineProperty(globalThis, "localStorage", { configurable: true, value: { getItem: (key:string) => data.get(key) ?? null, setItem: (key:string, value:string) => data.set(key,value) } });
const html = (node: React.ReactNode) => renderToStaticMarkup(<LangProvider>{node}</LangProvider>);
const created = listing("custody");
created.tradeTimeoutSeconds = 3600;
assert.deepEqual(ecashHoldingPeriod(created), { seconds: 3600 }, "pre-lock duration comes from committed timeout, not the listing expiry");
const locked = { ...created, lock: { ...created.lock, lockedAt: created.createdAt + 100 }, expiresAt: created.createdAt + 3700 };
assert.deepEqual(ecashHoldingPeriod(locked), { deadline: locked.expiresAt });
assert.deepEqual(ecashHoldingPeriod({ ...created, parent: "circle", expiresAt: created.createdAt + 30*86400 }), { deadline: created.createdAt + 30*86400 });
const missing = html(<EcashCustody />);
assert.match(missing, /guardian count unknown/); assert.doesNotMatch(missing, /0 guardians|safe|secure/);
assert.match(missing, /aria-expanded="false"/); assert.doesNotMatch(missing, /IOU/, "complex explanation is collapsed initially");
assert.match(html(<BitcoinCustody refundHeight={123456} />), /refund at block 123456/);
assert.match(html(<BitcoinCustody />), /refund block not available yet/);
for (const outcome of ["timeout", "error", "empty", "aborted"] as const) {
 const view=html(<LivenessSignal liveness={null} outcome={outcome} onRetry={()=>{}} />);
 assert.doesNotMatch(view,/role="img"|score 0|become an arbiter/i);
 assert.match(view,/couldn.t check yet/); assert.match(view,/Try again/);
}
const checking=html(<LivenessSignal liveness={null} loading />);
assert.doesNotMatch(checking,/role="img"/); assert.match(checking,/checking who/);
const genuineZero=computeChamaLiveness("test",[],new Map(),900000);
assert.match(html(<LivenessSignal liveness={genuineZero} />), /role="img"/);
assert.doesNotMatch(html(<LivenessSignal liveness={genuineZero} outcome="timeout" onRetry={()=>{}} />), /role="img"/, "a failed refresh must not paint its cached score as a completed check");
for (const lang of ["en","es","fr","sw"] as const) for(const key of ["custody.what","custody.notes","custody.faqTitle","bond.livenessRetry"]) assert.notEqual(translate(lang,key),key);
const secret = new Uint8Array(32).fill(51), pubkey=getPublicKey(secret);
const unsigned=buildBondAnnouncementEvent({pubkey,community:"test",ownerXonly:pubkey,lockUntil:950000,amountSats:1000n,network:MAINNET,address:"public test address",createdAt:1700000000});
const event=finalizeEvent(unsigned,secret);
const base={community:"test",network:MAINNET,fetchJson:async()=>900000,readAnnouncements:async()=>({events:[event],complete:true})};
await assert.rejects(readLivenessBonds({...base,readAnnouncements:async()=>({events:[],complete:false})}),/incomplete/);
await assert.rejects(readLivenessBonds({...base,fetchJson:async()=>{throw Error("explorer unavailable");}}),/explorer unavailable/);
await assert.rejects(readLivenessBonds({...base,verify:async()=>{throw Error("bond read failed");}}),/bond read failed/);
assert.equal((await readLivenessBonds({...base,readAnnouncements:async()=>({events:[],complete:true})})).bonds.length,0,"a complete empty reading is honestly zero");
assert.equal((await readLivenessBonds({...base,verify:async()=>null})).bonds.length,0,"invalid bond domain is not a missing explorer reading");
await assert.rejects(readLivenessBonds({...base,verify:async(_a,c)=>{await c.fetchJson('/address/test/utxo');return null;},fetchJson:async path=>path==='/blocks/tip/height'?900000:{bad:true}}),/unreadable bond deposit/);
resetLivenessCoordinator();
const failed = await loadCoordinatedLiveness('test',async()=>{throw Error('temporary failure');});
assert.equal(failed.liveness,null); assert.equal(failed.outcome,'error'); assert.equal(readCachedLiveness('test'),null);
const syncFailed = await loadCoordinatedLiveness('sync-throw',()=>{throw Error('sync failure');});
assert.equal(syncFailed.outcome,'error'); assert.equal(syncFailed.liveness,null);
const recovered=await loadCoordinatedLiveness('test',async()=>genuineZero);
assert.equal(recovered.liveness?.arbiterCount,0); assert.equal(recovered.outcome,'verified');
console.log("custody and liveness: unknown, retry, actual deadlines and incomplete evidence passed");
