import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import { OnchainEscrowPanel } from './panels/OnchainEscrowPanel.js';
import { prepareFundingOnce } from './panels/OnchainTradeControls.js';
import { FundingModalShell } from './components/FundingModalShell.js';
import { LangProvider } from '../i18n/index.js';
import type { OnchainEscrowView } from '../escrow-engine/onchain-escrow-view.js';
const view = { stage:'awaiting-funding', address:'bc1p'+'a'.repeat(58), expectedSats:28000n, viewerFunds:true, blockers:[] } as unknown as OnchainEscrowView;
const render = (viewerFunds:boolean, note?:string) => renderToStaticMarkup(<LangProvider><FundingModalShell onClose={()=>{}}><OnchainEscrowPanel view={{...view,viewerFunds}} network="mainnet" checking onCheckFunding={()=>{}} fundingNote={note} /></FundingModalShell></LangProvider>);
const html = render(true, 'Couldn’t check the deposit yet — retrying');
assert.match(html,/Send 28,000 sats to this address/);
assert.match(html,/funding-check-spinner/);
assert.match(html,/Why this address is safe/);
assert.ok(html.includes(view.address!),'copy retains the full locally verified address during failure');
assert.match(html,/Couldn’t check the deposit yet/);
assert.doesNotMatch(html,/Prepare deposit address/);
assert.doesNotMatch(render(false),/class="funding-check-spinner"/,'read-only viewer has no check button');
let calls=0; let finish!:()=>void;
const prepare=()=>{calls++;return new Promise<void>(resolve=>{finish=resolve;});};
const first=prepareFundingOnce('trade',prepare), second=prepareFundingOnce('trade',prepare);
await Promise.resolve(); assert.equal(calls,1); finish(); await Promise.all([first,second]);
await assert.rejects(prepareFundingOnce('trade',async()=>{throw Error('offline');}));
await prepareFundingOnce('trade',async()=>{calls++;}); assert.equal(calls,2,'manual retry works after failure');
console.log('PASS on-chain funding card: shared shell, address survives timeout, read-only mode, deduplicated preparation and retry');
