import assert from 'node:assert/strict';
import {renderToStaticMarkup} from 'react-dom/server';
import {LangProvider} from '../i18n/index.js';
import {TradePaymentDetails} from './components/TradePaymentDetails.js';
import {LiveTradeSurface} from './screens/LiveTradeSurface.js';
import {LockPaymentDetailsModal} from './panels/LockPaymentDetailsModal.js';
import {confirmLockPaymentChoice,enterLockPaymentDetails,readLockPaymentChoice,handleMatchesTrade,confirmedLockPaymentFields} from '../payments/lock-payment-details.js';
import {getSavedHandle,addSavedHandle,deleteSavedHandle} from '../payments/saved-handles.js';
import {setLocalStorageUserScope} from '../storage/user-scope.js';
import {EscrowFedimintBridge} from '../fedimint/escrow-bridge.js';
import type {EscrowClient,Signer} from '../escrow-engine/escrow-client.js';
import type {FedimintClient} from '../fedimint/fedimint-client.js';
import {EscrowStatus,Role,type EscrowState} from '../escrow-engine/types.js';
const storage=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)}});
setLocalStorageUserScope('trade-flow');
const seller='a'.repeat(64),buyer='b'.repeat(64),arbiter='c'.repeat(64),now=Math.floor(Date.now()/1000);
const state={id:'payment-trade',provenance:'chain',status:EscrowStatus.LOCKED,category:'p2p-trade',amountMsats:1000000,description:'test',paymentMethods:['strike'],createdAt:now,expiresAt:now+86400,community:'us-usd',initiator:{pubkey:seller},participants:{buyer,seller,arbiter},joinHolds:{},lock:{lockedAt:now,notesHash:'locked',handle:null},votes:{},eventChain:[],chatMessages:[],communityArbiters:[arbiter]} as unknown as EscrowState;
const render=(node:React.ReactNode)=>renderToStaticMarkup(<LangProvider>{node}</LangProvider>);
assert.equal(readLockPaymentChoice(state),null,'no default consent');
assert.throws(()=>confirmLockPaymentChoice(state,{savedHandleId:'missing'}));
const wrong=addSavedHandle('revtag','wrong-user');assert.equal(handleMatchesTrade(wrong,state),false);
assert.throws(()=>confirmLockPaymentChoice(state,{savedHandleId:wrong.id}),'other-method handle never silently attaches');
assert.throws(()=>enterLockPaymentDetails(state,'strike',''));
const choice=enterLockPaymentDetails(state,'strike','jetty');assert.ok('savedHandleId' in choice);
assert.deepEqual(readLockPaymentChoice(state),choice,'confirmed choice survives reopen for on-chain lock');
const saved=getSavedHandle(choice.savedHandleId)!;
assert.deepEqual(confirmedLockPaymentFields(state),{handleId:saved.id,handle:saved.handle,rail:saved.rail,handleNetworks:saved.networks},'on-chain LOCK uses the confirmed encrypted-handle fields');
const withHandle={...state,lock:{...state.lock,handle:{value:saved.handle,rail:saved.rail,id:saved.id,networks:[]}}};
const handleHtml=render(<TradePaymentDetails state={withHandle}/>);assert.match(handleHtml,/jetty/);assert.match(handleHtml,/Strike/);
const buyerRoom=(trade:EscrowState,pubkey=buyer)=>render(<LiveTradeSurface state={trade} pubkey={pubkey} onBack={()=>{}} onOpenFullView={()=>{}} onVote={async()=>{}} onSendChat={()=>{}}/>);
assert.match(buyerRoom(withHandle),/jetty/,'buyer sees committed LOCK handle');
assert.doesNotMatch(buyerRoom(withHandle,'d'.repeat(64)),/jetty/,'outsider never sees payment details');
deleteSavedHandle(saved.id);assert.equal(readLockPaymentChoice(state),null,'stale handle is not silently reused');
assert.throws(()=>confirmedLockPaymentFields(state),/changed/,'stale on-chain confirmation never silently loses the handle');
let moneyCalls=0;
const bridge=new EscrowFedimintBridge({getState:()=>({...state,status:EscrowStatus.CREATED}),lockEscrow:()=>{moneyCalls++;}} as unknown as EscrowClient,{createEscrowLock:()=>{moneyCalls++;},spendNotes:()=>{moneyCalls++;}} as unknown as FedimintClient,{} as Signer);
await assert.rejects(bridge.preflightLock(state.id,{savedHandleId:saved.id}),/changed/);
await assert.rejects(bridge.lockAndPublish(state.id,{savedHandleId:saved.id}),/changed/);
assert.equal(moneyCalls,0,'stale payment handle refuses before a spend or LOCK');
confirmLockPaymentChoice(state,{inChat:true});assert.deepEqual(readLockPaymentChoice(state),{inChat:true});
assert.deepEqual(confirmedLockPaymentFields(state),{},'chat fallback uses the existing no-handle LOCK shape');
const chatHtml=buyerRoom(state);assert.match(chatHtml,/Strike/);assert.match(chatHtml,/chat before sending money/,'buyer sees methods and chat fallback when LOCK carries no handle');
const modal=render(<LockPaymentDetailsModal state={state} onClose={()=>{}} onConfirm={()=>{}}/>);
assert.match(modal,/I’ll send it in chat/);assert.match(modal,/autocomplete="off"/i);assert.match(modal,/disabled=""/,'empty entered details cannot continue');
setLocalStorageUserScope('other-identity');assert.equal(readLockPaymentChoice(state),null,'lock choice is identity scoped');
console.log('PASS trade flow payment details: explicit choice, validated method, private handle reveal, participant-only buyer view, no-handle chat fallback, stale choice and identity isolation');
