import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const signInReliability = {
  en_US:
    'Reliability: tapping a web notification now opens its trade inside the existing page instead of reloading the memory-only browser session, and a failed first connection no longer blocks every retry until refresh. ',
  es_ES:
    'Fiabilidad: al tocar una notificación web, su intercambio ahora se abre dentro de la página existente en vez de recargar la sesión del navegador, que solo vive en memoria; además, un primer intento de conexión fallido ya no bloquea todos los reintentos hasta actualizar la página. ',
  de_DE:
    'Zuverlässigkeit: Beim Antippen einer Web-Benachrichtigung öffnet sich der Handel nun innerhalb der bestehenden Seite, statt die nur im Arbeitsspeicher gehaltene Browser-Sitzung neu zu laden; außerdem blockiert ein fehlgeschlagener erster Verbindungsversuch nicht mehr alle weiteren Versuche bis zum Neuladen. ',
  pl_PL:
    'Niezawodność: dotknięcie powiadomienia internetowego otwiera teraz transakcję w istniejącej stronie zamiast przeładowywać sesję przeglądarki przechowywaną tylko w pamięci, a nieudane pierwsze połączenie nie blokuje już wszystkich kolejnych prób aż do odświeżenia. ',
  fr_FR:
    "Fiabilité : toucher une notification web ouvre désormais l'échange dans la page existante au lieu de recharger la session du navigateur conservée uniquement en mémoire ; de plus, un premier échec de connexion ne bloque plus toutes les nouvelles tentatives jusqu'à l'actualisation. ",
} as const

export const current = VersionInfo.of({
  version: '6.1.0:0',
  releaseNotes: {
    en_US:
      signInReliability.en_US +
      "This release is recovery honesty, a security hardening, and interface polish — and unlike 6.0.1 its centrepiece is not a browser-only bug, so it matters here as much as anywhere. When a settled trade's ecash notes are reported already spent but the wallet comes up short, Chama no longer guesses where the money went: it asks the federation directly by trying to reissue the notes, and reports only what that answer proves — recovered to your balance, provably dead, or an open question kept for your records rather than written off. The recovery cards that used to claim your money 'most likely landed on another device' without ever testing it now state only what was checked. Security: an old friend-wallet invite link — a URL that could silently point a browser wallet at someone else's node — is no longer honoured; any such link is stripped on load and never applied, and the manual node-connection card now sits behind power-user mode. This package is unaffected by that path and keeps running its own native Rust bridge throughout. Interface: the attention pill now names the trade it will open — amount and community — instead of jumping you somewhere unannounced; the first image sent in a fresh chat is no longer dropped before the other side has opened the trade; and the trade view's upper and lower panels can now be dragged to give either one more room. Unchanged for this package: three co-located clients, each with its own native Fedimint bridge, no account server and no custody role.",
    es_ES:
      signInReliability.es_ES +
      "Esta versión trae honestidad en la recuperación, un refuerzo de seguridad y pulido de la interfaz — y, a diferencia de la 6.0.1, su pieza central no es un fallo exclusivo del navegador, así que aquí importa tanto como en cualquier sitio. Cuando las notas ecash de un intercambio liquidado se declaran ya gastadas pero el monedero se queda corto, Chama ya no adivina a dónde fue el dinero: se lo pregunta directamente a la federación intentando reacuñar las notas, e informa solo de lo que esa respuesta demuestra — recuperado a tu saldo, muerto de forma comprobada, o una cuestión abierta que se conserva en tus registros en lugar de darse por perdida. Las tarjetas de recuperación que antes afirmaban que tu dinero «probablemente llegó a otro dispositivo» sin haberlo comprobado ahora solo indican lo que se verificó. Seguridad: un antiguo enlace de invitación de monedero de un amigo — una URL que podía apuntar en silencio un monedero de navegador al nodo de otra persona — ya no se acepta; cualquier enlace así se elimina al cargar y nunca se aplica, y la tarjeta de conexión manual a un nodo queda ahora tras el modo avanzado. Este paquete no se ve afectado por esa vía y sigue ejecutando su propio puente Rust nativo en todo momento. Interfaz: la píldora de atención ahora nombra el intercambio que va a abrir — importe y comunidad — en lugar de llevarte a algún sitio sin avisar; la primera imagen enviada en un chat nuevo ya no se pierde antes de que la otra parte haya abierto el intercambio; y los paneles superior e inferior de la vista de intercambio ahora se pueden arrastrar para dar más espacio a cualquiera de ellos. Sin cambios para este paquete: tres clientes co-ubicados, cada uno con su propio puente nativo de Fedimint, sin servidor de cuentas y sin rol de custodia.",
    de_DE:
      signInReliability.de_DE +
      "Diese Version bringt Ehrlichkeit bei der Wiederherstellung, eine Sicherheitshärtung und Feinschliff der Oberfläche — und anders als 6.0.1 ist ihr Kernstück kein reiner Browser-Fehler, also zählt sie hier genauso wie überall. Wenn die E-Cash-Noten eines abgeschlossenen Handels als bereits ausgegeben gemeldet werden, die Wallet aber zu wenig hält, rät Chama nicht mehr, wohin das Geld ging: Es fragt die Föderation direkt, indem es versucht, die Noten neu zu prägen, und meldet nur, was diese Antwort beweist — in dein Guthaben zurückgeholt, nachweislich verloren, oder eine offene Frage, die für deine Unterlagen behalten statt abgeschrieben wird. Die Wiederherstellungskarten, die früher behaupteten, dein Geld sei „wahrscheinlich auf einem anderen Gerät gelandet\", ohne es je zu prüfen, sagen jetzt nur noch, was tatsächlich geprüft wurde. Sicherheit: ein alter Freund-Wallet-Einladungslink — eine URL, die eine Browser-Wallet stillschweigend auf den Knoten einer anderen Person richten konnte — wird nicht mehr akzeptiert; ein solcher Link wird beim Laden entfernt und nie angewendet, und die Karte zur manuellen Knotenverbindung liegt jetzt hinter dem Power-User-Modus. Dieses Paket ist von diesem Weg nicht betroffen und betreibt durchgehend seine eigene native Rust-Bridge. Oberfläche: die Aufmerksamkeits-Pille benennt jetzt den Handel, den sie öffnet — Betrag und Gemeinschaft — statt dich unangekündigt woandershin zu springen; das erste Bild in einem frischen Chat geht nicht mehr verloren, bevor die Gegenseite den Handel geöffnet hat; und die obere und untere Fläche der Handelsansicht lassen sich nun ziehen, um einer von beiden mehr Raum zu geben. Unverändert für dieses Paket: drei am selben Ort betriebene Clients, jeder mit eigener nativer Fedimint-Bridge, ohne Kontoserver und ohne Verwahrfunktion.",
    pl_PL:
      signInReliability.pl_PL +
      "To wydanie to uczciwość przy odzyskiwaniu, wzmocnienie bezpieczeństwa i dopracowanie interfejsu — i w przeciwieństwie do 6.0.1 jego sednem nie jest błąd występujący tylko w przeglądarce, więc liczy się tu tak samo jak wszędzie. Gdy noty ecash rozliczonej transakcji są zgłaszane jako już wydane, a w portfelu brakuje tej kwoty, Chama nie zgaduje już, dokąd trafiły pieniądze: pyta federację wprost, próbując ponownie wybić noty, i raportuje tylko to, co ta odpowiedź udowadnia — odzyskane do twojego salda, w sposób sprawdzony martwe, albo otwartą kwestię zachowaną w twoich zapisach zamiast spisaną na straty. Karty odzyskiwania, które wcześniej twierdziły, że twoje pieniądze „prawdopodobnie trafiły na inne urządzenie\", nigdy tego nie sprawdzając, teraz podają tylko to, co faktycznie zweryfikowano. Bezpieczeństwo: stary link zapraszający do portfela znajomego — adres URL, który mógł po cichu skierować portfel przeglądarkowy do węzła innej osoby — nie jest już akceptowany; każdy taki link jest usuwany przy wczytywaniu i nigdy nie stosowany, a karta ręcznego łączenia z węzłem znajduje się teraz za trybem zaawansowanym. Tego pakietu ta ścieżka nie dotyczy i przez cały czas uruchamia on własny natywny mostek Rust. Interfejs: pigułka uwagi nazywa teraz transakcję, którą otworzy — kwotę i społeczność — zamiast przenosić cię gdzieś bez zapowiedzi; pierwszy obraz wysłany na świeżym czacie nie jest już gubiony, zanim druga strona otworzy transakcję; a górny i dolny panel widoku transakcji można teraz przeciągać, aby dać jednemu z nich więcej miejsca. Bez zmian w tym pakiecie: trzej klienci w jednym miejscu, każdy z własnym natywnym mostkiem Fedimint, bez serwera kont i bez roli powiernika.",
    fr_FR:
      signInReliability.fr_FR +
      "Cette version apporte de l'honnêteté dans la récupération, un renforcement de la sécurité et des finitions d'interface — et contrairement à la 6.0.1, sa pièce maîtresse n'est pas un bug propre au navigateur, elle compte donc ici autant qu'ailleurs. Lorsque les notes ecash d'un échange réglé sont signalées comme déjà dépensées mais que le portefeuille est en déficit, Chama ne devine plus où est allé l'argent : il interroge directement la fédération en tentant de réémettre les notes, et ne rapporte que ce que cette réponse prouve — récupéré sur votre solde, mort de façon avérée, ou une question ouverte conservée dans vos archives plutôt que passée par pertes et profits. Les cartes de récupération qui affirmaient auparavant que votre argent « a probablement atterri sur un autre appareil » sans jamais l'avoir vérifié n'indiquent désormais que ce qui a été contrôlé. Sécurité : un ancien lien d'invitation de portefeuille d'ami — une URL qui pouvait diriger en silence un portefeuille de navigateur vers le nœud de quelqu'un d'autre — n'est plus accepté ; un tel lien est supprimé au chargement et jamais appliqué, et la carte de connexion manuelle à un nœud se trouve maintenant derrière le mode expert. Ce paquet n'est pas concerné par cette voie et continue d'exécuter sa propre passerelle Rust native de bout en bout. Interface : la pastille d'attention nomme désormais l'échange qu'elle va ouvrir — montant et communauté — au lieu de vous emmener ailleurs sans prévenir ; la première image envoyée dans un chat neuf n'est plus perdue avant que l'autre partie ait ouvert l'échange ; et les panneaux supérieur et inférieur de la vue d'échange peuvent maintenant être glissés pour donner plus de place à l'un ou à l'autre. Inchangé pour ce paquet : trois clients co-localisés, chacun avec sa propre passerelle Fedimint native, sans serveur de comptes ni rôle de dépositaire.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
