import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '6.0.1:0',
  releaseNotes: {
    en_US:
      'The headline fix in this release does not affect this package, and that is worth stating plainly: ecash escrows created in a web browser were being returned to their funder the moment they were created, because a 90-day auto-cancel deadline overflowed the browser\'s 32-bit timer and read as "immediately." Those trades published a lock and appeared funded while holding nothing. This package runs the Rust wallet on your own server, which never had that limit, so escrows here were held correctly throughout. The deadline is now 14 days and Chama refuses to spend notes at all if a deadline would exceed what a browser can represent — checked before any note is created. Also in this release: funding by Lightning now works from a browser, which matters here because that is how you reach each client — Chama had been demanding a vetting flag browser wallets are never given, so the control existed and quietly did nothing on every federation, and receiving now accepts the trust a federation publishes about its own gateways while still refusing a route nothing vouches for. Sats can no longer lock into a trade held on a different federation: the notes are read back after minting and compared against the trade\'s own federation, and on a mismatch they return to your wallet with no lock published. A revoked remote-node link now falls back to your own wallet instead of failing to start. Browse preferences are stored per identity, so a second npub on the same client starts from the defaults. Unchanged for this package: three co-located clients, each with its own native Fedimint bridge, no account server and no custody role.',
    es_ES:
      'La corrección principal de esta versión no afecta a este paquete, y conviene decirlo con claridad: los depósitos en ecash creados en un navegador web volvían a quien los financió en el momento mismo de crearse, porque un plazo de cancelación automática de 90 días desbordaba el temporizador de 32 bits del navegador y se leía como «inmediatamente». Esos intercambios publicaban un bloqueo y parecían financiados sin contener nada. Este paquete ejecuta el monedero en Rust en tu propio servidor, que nunca tuvo ese límite, así que aquí los depósitos se mantuvieron correctamente en todo momento. El plazo ahora es de 14 días y Chama se niega a gastar notas si un plazo excediera lo que un navegador puede representar — se comprueba antes de crear cualquier nota. También en esta versión: financiar por Lightning ya funciona desde un navegador, lo que aquí importa porque así es como llegas a cada cliente — Chama exigía una marca de verificación que los monederos de navegador nunca reciben, de modo que el control existía y no hacía nada en ninguna federación; ahora la recepción acepta la confianza que una federación publica sobre sus propias pasarelas y sigue rechazando una ruta que nadie avala. Los sats ya no pueden bloquearse en un intercambio alojado en otra federación: las notas se releen tras acuñarse y se comparan con la federación del propio intercambio, y si no coinciden vuelven a tu monedero sin publicar ningún bloqueo. Un enlace revocado a un nodo remoto ahora recurre a tu propio monedero en lugar de no arrancar. Las preferencias de Explorar se guardan por identidad, así que un segundo npub en el mismo cliente empieza con los valores por defecto. Sin cambios para este paquete: tres clientes en el mismo servidor, cada uno con su propio puente nativo de Fedimint, sin servidor de cuentas y sin custodia.',
    de_DE:
      'Die wichtigste Korrektur dieser Version betrifft dieses Paket nicht, und das sei deutlich gesagt: In einem Webbrowser erstellte E-Cash-Treuhandeinlagen gingen im Moment ihrer Erstellung an den Einzahler zurück, weil eine Frist von 90 Tagen für den automatischen Abbruch den 32-Bit-Timer des Browsers überlief und als „sofort“ gelesen wurde. Diese Handel veröffentlichten eine Sperre und wirkten finanziert, hielten aber nichts. Dieses Paket betreibt die Rust-Wallet auf deinem eigenen Server, der diese Grenze nie hatte — die Treuhand wurde hier durchgehend korrekt gehalten. Die Frist beträgt jetzt 14 Tage, und Chama weigert sich, Noten überhaupt auszugeben, wenn eine Frist über dem läge, was ein Browser darstellen kann — geprüft, bevor eine Note entsteht. Ebenfalls in dieser Version: Aufladen per Lightning funktioniert nun aus dem Browser, was hier zählt, weil du jeden Client genau so erreichst — Chama verlangte ein Prüfkennzeichen, das Browser-Wallets nie erhalten, die Kontrolle existierte also und tat auf jeder Föderation stillschweigend nichts; der Empfang akzeptiert jetzt das Vertrauen, das eine Föderation über ihre eigenen Gateways veröffentlicht, und lehnt eine Route, für die niemand bürgt, weiterhin ab. Sats lassen sich nicht mehr in einen Handel auf einer anderen Föderation sperren: Die Noten werden nach dem Prägen zurückgelesen und mit der Föderation des Handels verglichen; bei Abweichung kehren sie in deine Wallet zurück, ohne dass eine Sperre veröffentlicht wird. Eine widerrufene Verbindung zu einem entfernten Knoten weicht jetzt auf deine eigene Wallet aus, statt den Start zu verweigern. Browse-Einstellungen werden pro Identität gespeichert, ein zweites npub auf demselben Client startet also mit den Standardwerten. Unverändert für dieses Paket: drei Clients am selben Ort, jeder mit eigener nativer Fedimint-Bridge, ohne Kontoserver und ohne Verwahrfunktion.',
    pl_PL:
      'Najważniejsza poprawka w tym wydaniu nie dotyczy tego pakietu i warto powiedzieć to wprost: depozyty ecash tworzone w przeglądarce wracały do osoby, która je sfinansowała, w tej samej chwili, w której powstawały, ponieważ 90-dniowy termin automatycznego anulowania przepełniał 32-bitowy licznik przeglądarki i był odczytywany jako „natychmiast”. Takie transakcje publikowały blokadę i wyglądały na sfinansowane, nie zawierając niczego. Ten pakiet uruchamia portfel w Ruście na twoim własnym serwerze, który nigdy nie miał tego ograniczenia — depozyty były tu przez cały czas trzymane poprawnie. Termin wynosi teraz 14 dni, a Chama w ogóle odmawia wydania not, jeśli termin przekroczyłby to, co przeglądarka potrafi zapisać — sprawdzane, zanim powstanie jakakolwiek nota. Ponadto w tym wydaniu: finansowanie przez Lightning działa już z przeglądarki, co ma tu znaczenie, bo właśnie tak docierasz do każdego klienta — Chama wymagała znacznika weryfikacji, którego portfele przeglądarkowe nigdy nie otrzymują, więc zabezpieczenie istniało i po cichu nic nie robiło w żadnej federacji; odbiór akceptuje teraz zaufanie, które federacja publikuje o własnych bramkach, a wciąż odrzuca trasę, za którą nikt nie ręczy. Sat-y nie mogą już zostać zablokowane w transakcji prowadzonej na innej federacji: noty są odczytywane po wybiciu i porównywane z federacją samej transakcji, a przy niezgodności wracają do twojego portfela i żadna blokada nie zostaje opublikowana. Unieważnione połączenie ze zdalnym węzłem korzysta teraz z twojego własnego portfela zamiast nie wystartować. Ustawienia przeglądania są zapisywane per tożsamość, więc drugi npub na tym samym kliencie zaczyna od wartości domyślnych. Bez zmian w tym pakiecie: trzej klienci w jednym miejscu, każdy z własnym natywnym mostkiem Fedimint, bez serwera kont i bez roli powiernika.',
    fr_FR:
      "Le correctif principal de cette version ne concerne pas ce paquet, et cela mérite d'être dit clairement : les séquestres en ecash créés dans un navigateur web revenaient à celui qui les avait financés à l'instant même de leur création, parce qu'un délai d'annulation automatique de 90 jours dépassait la capacité du minuteur 32 bits du navigateur et se lisait comme « immédiatement ». Ces échanges publiaient un verrou et paraissaient financés tout en ne contenant rien. Ce paquet exécute le portefeuille Rust sur votre propre serveur, qui n'a jamais eu cette limite : les séquestres y ont été tenus correctement du début à la fin. Le délai est désormais de 14 jours, et Chama refuse purement et simplement de dépenser des notes si un délai dépassait ce qu'un navigateur peut représenter — vérifié avant la création de la moindre note. Également dans cette version : le financement par Lightning fonctionne maintenant depuis un navigateur, ce qui compte ici puisque c'est ainsi que vous atteignez chaque client — Chama exigeait un indicateur de validation que les portefeuilles de navigateur ne reçoivent jamais, si bien que ce contrôle existait et ne faisait discrètement rien sur toutes les fédérations ; la réception accepte désormais la confiance qu'une fédération publie au sujet de ses propres passerelles, tout en refusant toujours une route dont personne ne se porte garant. Les sats ne peuvent plus être verrouillés dans un échange tenu sur une autre fédération : les notes sont relues après frappe et comparées à la fédération de l'échange lui-même, et en cas d'écart elles reviennent dans votre portefeuille sans qu'aucun verrou ne soit publié. Un lien révoqué vers un nœud distant se rabat désormais sur votre propre portefeuille au lieu de ne pas démarrer. Les préférences de navigation sont enregistrées par identité : un second npub sur le même client démarre donc sur les valeurs par défaut. Inchangé pour ce paquet : trois clients co-localisés, chacun avec sa propre passerelle Fedimint native, sans serveur de comptes ni rôle de dépositaire.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
