import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
const browser=await puppeteer.launch({executablePath:process.env.CHAMA_BROWSER??'/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',headless:true,protocolTimeout:15000,args:['--no-sandbox']});
try {
 const page=await browser.newPage(); page.on("pageerror",e=>console.error(e.message)); page.on("console",m=>{if(m.type()==="error")console.error(m.text());}); page.setDefaultTimeout(10000); await page.setViewport({width:390,height:844});
 const base=process.env.CHAMA_PREVIEW??'http://127.0.0.1:3000';
 const clickText=async(text)=>{await page.waitForFunction(text=>[...document.querySelectorAll('button')].some(b=>b.textContent.trim()===text),{},text);await page.evaluate(text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text).click(),text);};
 await page.goto(`${base}/tests/brief01/`);await page.waitForSelector('[data-funding-rail=lightning]');
 await clickText('See all Lightning options'); console.log('opened Lightning');
 await page.waitForSelector('input[placeholder="you@wallet.app or lnurl1…"]');
 await page.type('input[placeholder="you@wallet.app or lnurl1…"]','alice@example.com');
 await page.click('button[aria-label=Back]');
 await clickText('See all Lightning options'); console.log('opened Lightning');
 assert.equal(await page.$eval('input[placeholder="you@wallet.app or lnurl1…"]',e=>e.value),'alice@example.com');
 await page.click('button[aria-label=Back]');
 await page.click('[data-funding-rail=onchain]'); console.log('selected onchain');
 await page.click('button.payment-button');await page.waitForSelector('textarea[placeholder="bc1..."]');
 await page.type('textarea[placeholder="bc1..."]','bc1qmy-draft');
 await page.click('button[aria-label=Back]');
 assert.equal(await page.$eval('[data-funding-rail=onchain]',e=>e.getAttribute('aria-selected')),'true');
 await page.click('button.payment-button');
 assert.equal(await page.$eval('textarea[placeholder="bc1..."]',e=>e.value),'bc1qmy-draft');
 await page.click('button[aria-label=Back]');
 await page.click('[data-funding-rail=ecash]');await page.click('button.payment-button');
 await page.waitForSelector('button[aria-label=Back]');
 assert.equal(await page.evaluate(()=>window.imported),undefined);
 await page.screenshot({path:'/tmp/chama-brief01-claim.png'});
 await page.click('button[aria-label=Back]');
 assert.equal(await page.evaluate(()=>window.cardCloses),0);
 assert.equal(await page.evaluate(()=>window.imported),undefined);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 await clickText('×');assert.equal(await page.evaluate(()=>window.cardCloses),1);
 await page.goto(`${base}/tests/brief01/?funding=1`);await page.waitForSelector('.payment-card img');
 const qr=await page.$eval('.payment-card img',e=>e.src);
 await page.click('button[aria-label=Back]');
 await clickText('Show payment request');
 assert.equal(await page.$eval('.payment-card img',e=>e.src),qr);
 assert.deepEqual(await page.evaluate(()=>window.calls),['lightning']);
 assert.equal(await page.evaluate(()=>window.aborted),undefined,'Back preserves the payment watch');
 assert.equal(await page.evaluate(()=>window.cardCloses),0);
 await page.screenshot({path:'/tmp/chama-brief01-funding.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
 console.log('PASS phone-width Back: Lightning/on-chain drafts, ecash without import, funding QR and live watch preserved; close remains separate');
} catch(e) { console.error(e); process.exitCode=1; } finally { browser.process()?.kill(); }
