import assert from 'node:assert/strict';
import { walletUri, openWalletLink, nativeWalletLinks } from './wallet-link.js';
assert.equal(walletUri('LNBC123','lightning'),'lightning:LNBC123');
assert.equal(walletUri('LIGHTNING:LNBC123','lightning'),'lightning:LNBC123');
assert.equal(walletUri('bitcoin:bc1qexample?amount=0.001','onchain'),'bitcoin:bc1qexample?amount=0.001');
assert.equal(walletUri('bc1qexample','onchain'),'bitcoin:bc1qexample');
assert.equal(nativeWalletLinks(), false, 'web keeps copy behavior');
await assert.rejects(openWalletLink('https://example.com'), /Invalid payment link/);
console.log('PASS native wallet URI boundary and web fallback');
const { openWalletOrCopy } = await import('./wallet-link.js');
let copied = 0;
const copy = async () => { copied++; return true; };
let forwarded: unknown[] = [];
assert.equal(await openWalletOrCopy('lightning:LNBC123', copy, async (...args) => { forwarded = args; }), null);
assert.deepEqual(forwarded, ['lightning:LNBC123'], 'payment activation uses VIEW, never a share request');
assert.equal(copied, 0, 'opening a wallet does not overwrite the clipboard');
const missing = async () => { throw Error('NO_WALLET'); };
assert.equal(await openWalletOrCopy('lightning:LNBC123', copy, missing), 'Copied — no wallet on this phone opens Lightning links');
assert.equal(copied, 1);
assert.match((await openWalletOrCopy('bitcoin:bc1qexample', async () => false, missing))!, /^No wallet.*Copy the payment details manually/);
console.log('PASS wallet handoff and truthful automatic clipboard fallback');
